// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/FirmanHaris/api_e_learning/app/v1"
	"github.com/FirmanHaris/api_e_learning/app/v1/user/repository"
	"github.com/FirmanHaris/api_e_learning/app/v1/user/service"
	"github.com/labstack/echo/v4"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitializeV1RouteHandler(context2 context.Context, echo2 *echo.Echo, database *mongo.Database) v1.V1RouteHandler {
	userRepository := repository.NewUserRepository(database)
	userService := service.NewUserService(userRepository)
	v1RouteHandler := v1.NewV1RouteHandler(userService, echo2, context2, database)
	return v1RouteHandler
}
